### ISSUE TITLE
Request has to be done 2 times ?

### ISSUE THREAD

**Issue by jeremylagrue** [sendgrid/ruby-http-client#1]
I there, I'm probably a early adopter I have a feed back. Thank's for your attention.
#### Issue Summary

I'm using the http client with Contact API and I get a 404 for the first call and the second time it works.
#### Steps to Reproduce

```
    headers = {'Authorization'=> 'Bearer MYBEARER, 'Content-Type' => 'application/json'}
    host = 'https://api.sendgrid.com'
    client = SendGrid::Client.new(host: host, request_headers: headers, url_path: ['contactdb', 'lists'])

    query_params = {page_size: 1000, page: 1}
    response = client.version('v3').contactdb.lists.get(query_params: query_params)
    puts response.status_code #give 404
    puts response.response_body

    response = client.version('v3').contactdb.lists.get(query_params: query_params)
    # works
    lists = JSON.parse(response.response_body)
```

I hope my code.
#### Technical details:
- ruby_http_client (1.1.0)
- Ruby Version: 2.2.0

**Comment by thinkingserious** [comment]
Can you please try:
`client = SendGrid::Client.new(host: host, request_headers: headers)`

**Comment by jeremylagrue** [comment]
It look's good. I can't remember where I found the idea to user this url_path array.
Thank's

**Comment by thinkingserious** [comment]
@jeremylagrue if you happen to figure out where, please let me know. The URL path should not be passed in that way. Thanks!
