### ISSUE TITLE
Release sometime soon?

### ISSUE THREAD

**Issue by gareth** [sendgrid/ruby-http-client#109]
Hi!

I enjoy using Sendgrid and I'm keen to hook into it programatically.

However, this gem seems to be a bit stalled. It's been nearly 23 months since the [last version bump](https://github.com/sendgrid/ruby-http-client/commit/078a50fcaf92497cd297ddd248c6ff71a548aba7) and in that time [19 pull requests](https://github.com/sendgrid/ruby-http-client/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3E2017-10-30+) have been successfully merged (including one that I'm [particularly interested in](https://github.com/sendgrid/ruby-http-client/pull/20) because it unblocks [a pending issue](https://github.com/sendgrid/sendgrid-ruby/issues/172) in your core Ruby gem)

I'm aware that by the magic of Ruby I can fix my immediate issue, but I wondered what the status of this library was, given that it's how you [recommend interacting with the API](https://sendgrid.com/docs/for-developers/sending-email/v3-ruby-code-example/) from Ruby

**Comment by childish-sambino** [comment]
We're now releasing regularly. About every 2 weeks if there are merged PRs.

**Comment by gareth** [comment]
Thanks! Great news! 🎉
