### ISSUE TITLE
Breaking Change in build_request?

### ISSUE THREAD

**Issue by DanielWright** [sendgrid/ruby-http-client#119]
### Issue Summary
Prior to #95 being merged, we had code like the following that worked:

```
sendgrid.patch(request_body: an_array)
```

This worked because `an_array` would, along the way to Net::HTTP, be encoded to JSON. #95 changed this behavior, as now only hashes are automatically JSON-encoded.

Was this change in behavior intentional, or was our usage unexpected?

**Comment by childish-sambino** [comment]
Duplicates #117
