### ISSUE TITLE
[BUG] Proxy is returning non unicode characters

### ISSUE THREAD

**Issue by garyzhuge** [sendgrid/ruby-http-client#123]
Hi, 
I am currently trying to use the scraperapi.com's proxy address. However, when I do 
`client = SendGrid::Client.new(host: 'https://api.scraperapi.com/?api_key=API_KEY&premium=false&render=false&autoparse=false&keep_headers=true&url=https://api.headway.co/user-insurance&scraper_sdk=ruby')`

I get weird non-unicode characters in the response body but a 200 code. 

If however, I use the method of adding proxy_options in the init the call simply fails with 500. Does anyone have any idea?

**Comment by garyzhuge** [comment]
[https://cln.sh/Jc4CNx](url) here is the link to the weird characters 

The proxy service I am using asks me to disable SSL, does this have anything to do with it?

**Comment by JenniferMah** [comment]
@garyzhuge 
Could you provide more details, library/SDK versions, code samples, and links for what you're trying to accomplish?
