### ISSUE TITLE
Timeout configuration

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/ruby-http-client#13]
Please see [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/172).

**Comment by guille** [comment]
Hey @thinkingserious I've submitted a PR. Let me know what you think!

**Comment by jrectenwald** [comment]
Hey @thinkingserious, I took a stab at this as well in this [PR](https://github.com/sendgrid/ruby-http-client/pull/20).

**Comment by thinkingserious** [comment]
Hi @jrectenwald,

Could you please summarize what is different from @guille's implementation. I'd love to figure out a way to get both of your work recognized.

**Comment by jrectenwald** [comment]
The only difference is that the attribute names aren't hard coded in, so users would be able to set values for attributes other than read_timeout or open_timeout.

**Comment by thinkingserious** [comment]
Thanks for the clarification @jrectenwald,

I do like the idea of passing in `http_options` for the flexibility. 

What are your thoughts @guille? You have dibs since you submitted first :)

**Comment by guille** [comment]
Hey, if you like the idea I'm okay with merging that instead of mine, especially now that his PR has tests.
