### ISSUE TITLE
Headers on Response

### ISSUE THREAD

**Issue by hipsterelitist** [sendgrid/ruby-http-client#3]
#### Issue Summary

Hey, would it possible to get a usable version of the headers from a Sendgrid::Client response? Right now it is just dumping the contents of inspect, which is awfully awkward to parse into something usable.  Seems like an oversight.

https://github.com/sendgrid/ruby-http-client/blob/f3bad61ec64648ec6846159f99ceb1c8fae01d21/lib/ruby_http_client.rb#L16

```
@headers = response.to_hash.inspect
```

**Comment by thinkingserious** [comment]
Great catch @hipsterelitist!
