### ISSUE TITLE
Copy docs from a PR to create a USAGE.md file

### ISSUE THREAD

**Issue by mbernier** [sendgrid/ruby-http-client#44]
#### Issue Summary

Usage files are really nice when they exist in a repo, because it makes it really obvious where to look for information about how to use this tool. It can be frustrating when you expect this file to be there and it's not. 
Please add a USAGE.md file, you can see an example of this 
[here](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)

Please make sure you modify the file for this repo (hint: Most of this information should be in the README file)

Also, @fifiteen82726 [put together some AWESOME docs](https://github.com/sendgrid/ruby-http-client/pull/43) for how to install and run codeclimate locally, including a gif. Please add this to your new USAGE.md file.

**Comment by astromoose** [comment]
I’d love to help ;)

**Comment by williamn** [comment]
hi @astromoose are you working on this? If not, I'd happy to send a PR

**Comment by astromoose** [comment]
I was, yeah - but sadly RealWork™ has got in the way since :) go for it!

**Comment by williamn** [comment]
@astromoose sadly that's what happening to me now. I won't make to send a PR
