### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/ruby-http-client#83]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by irrationalRock** [comment]
Could I take a stab at this?

**Comment by thinkingserious** [comment]
It's all yours @irrationalRock, thanks!
