### ISSUE TITLE
Add a json_body helper that returns a JSON formatted response body

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/ruby-http-client#9]
#### Issue Summary

Right now, we return what the native `Net::HTTP` returns as a body, which is a raw string. We will keep that functionality, but add a helper such that you can say `response.json_body` to get a JSON formatted response body.

**Comment by thinkingserious** [comment]
We did this for headers already: https://github.com/sendgrid/ruby-http-client/pull/4

**Comment by diegoc-am** [comment]
As a JSON string or as a ruby hash?

**Comment by thinkingserious** [comment]
Hi @belfazt,

I think both would be helpful. `response.json_body` and `response.ruby_hash` or similar.

With Best Regards,

Elmer

**Comment by diegoc-am** [comment]
Hi @thinkingserious,

I think that I didn't make myself clear, should the call of `response.json_body` return a hash or a string?

If it returns a hash it should probably be named `to_h` or `to_hash` since it would make a little bit of more sense in my opinion

**Comment by thinkingserious** [comment]
Ah, maybe it should be called `response.to_json` and `response.to_hash`. But the thing is, we are just talking about converting the body, not the status code or headers. So maybe `response.body_to_json` and `response.body_to_hash` might be better?

**Comment by diegoc-am** [comment]
That makes sense, will submit a PR soon :)

**Comment by diegoc-am** [comment]
Should I update the version in the gemspec as well, or only the code?

**Comment by thinkingserious** [comment]
JuSt the code please, thanks!

**Comment by diegoc-am** [comment]
Submitted a pull request https://github.com/sendgrid/ruby-http-client/pull/12

Thanks
